# Generated by Django 4.1.5 on 2023-02-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_deck_deckcard'),
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partida_deck', to='card.deck', verbose_name='DECK')),
            ],
        ),
    ]
