# Generated by Django 4.1.5 on 2023-01-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ataque',
            field=models.IntegerField(verbose_name='PODER DE ATAQUE'),
        ),
        migrations.AlterField(
            model_name='card',
            name='defesa',
            field=models.IntegerField(verbose_name='PODER DE DEFESA'),
        ),
        migrations.AlterField(
            model_name='card',
            name='descricao',
            field=models.TextField(max_length=1000, verbose_name='DESCRICAO'),
        ),
        migrations.AlterField(
            model_name='card',
            name='imagem',
            field=models.FileField(upload_to='cards', verbose_name='IMAGEM'),
        ),
        migrations.AlterField(
            model_name='card',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='NOME DA CARTA'),
        ),
        migrations.AlterField(
            model_name='card',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.tipo', verbose_name='TIPO'),
        ),
    ]
