# Generated by Django 4.1.5 on 2023-02-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
        ('card', '0002_alter_card_ataque_alter_card_defesa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='NOME DO DECK')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jogo.jogador', verbose_name='JOGADOR')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.card', verbose_name='CARD')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.deck', verbose_name='DECK')),
            ],
        ),
    ]
