# Generated by Django 4.1.5 on 2023-01-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ataque_positivo', models.IntegerField(verbose_name='AUMENTO DE ATAQUE')),
                ('defesa_positiva', models.IntegerField(verbose_name='AUMENTO DE DEFESA')),
                ('ataque_negativo', models.IntegerField(verbose_name='REDUÇÃO DE ATAQUE')),
                ('defesa_negativa', models.IntegerField(verbose_name='REDUÇÃO DE DEFESA')),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='NOME DO TERRENO')),
                ('imagem', models.FileField(upload_to='terreno', verbose_name='IMAGEM')),
                ('descricao', models.TextField(max_length=1000, verbose_name='DESCRICAO')),
                ('tipo_terreno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='terreno.tipodoterreno', verbose_name='TIPO DE TERRENO')),
            ],
        ),
    ]
